# ================================================================
#  SYNONYM MAP & TYPO MAP
# ================================================================

# Từ điển đồng nghĩa tiếng Việt → tag chuẩn (mở rộng cho người dùng VN)
SYNONYM_MAP = {
    # --- Nhu cầu / Use-case ---
    "gaming": "USE:gaming", "game": "USE:gaming", "choi game": "USE:gaming",
    "chơi game": "USE:gaming", "fps": "USE:gaming", "esport": "USE:gaming",
    "lien minh": "USE:gaming", "valorant": "USE:gaming", "genshin": "USE:gaming",
    "pubg": "USE:gaming", "lol": "USE:gaming", "csgo": "USE:gaming",
    "cs2": "USE:gaming", "dota": "USE:gaming", "minecraft": "USE:gaming",
    "gta": "USE:gaming", "fortnite": "USE:gaming", "overwatch": "USE:gaming",
    "lien quan": "USE:gaming", "liên quân": "USE:gaming",
    "free fire": "USE:gaming", "ff": "USE:gaming",
    "chien game": "USE:gaming", "chiến game": "USE:gaming",
    "cay game": "USE:gaming", "cày game": "USE:gaming",
    "cay rank": "USE:gaming", "cày rank": "USE:gaming",
    "stream game": "USE:gaming", "streaming": "USE:gaming",
    "chay mượt": "USE:gaming", "mượt": "USE:gaming",
    "may choi game": "USE:gaming", "máy chơi game": "USE:gaming",
    "laptop gaming": "USE:gaming",

    "van phong": "USE:office",  "văn phòng": "USE:office",
    "hoc tap": "USE:office", "học tập": "USE:office", "sinh vien": "USE:office",
    "sinh viên": "USE:office", "lam viec": "USE:office", "làm việc": "USE:office",
    "word excel": "USE:office", "office": "USE:office",
    "hoc online": "USE:office", "học online": "USE:office",
    "hoc truc tuyen": "USE:office", "học trực tuyến": "USE:office",
    "di hoc": "USE:office", "đi học": "USE:office",
    "lam bai": "USE:office", "làm bài": "USE:office",
    "soan thao": "USE:office", "soạn thảo": "USE:office",
    "powerpoint": "USE:office", "google docs": "USE:office",
    "zoom": "USE:office", "teams": "USE:office",
    "hop truc tuyen": "USE:office", "họp trực tuyến": "USE:office",
    "nhan vien": "USE:office", "nhân viên": "USE:office",
    "ke toan": "USE:office", "kế toán": "USE:office",
    "misa": "USE:office", "sap": "USE:office",
    "may lam viec": "USE:office", "máy làm việc": "USE:office",
    "may hoc": "USE:office", "máy học": "USE:office",
    "danh may": "USE:office", "đánh máy": "USE:office",
    "van thu": "USE:office", "văn thư": "USE:office",

    "do hoa": "USE:creative", "đồ hoạ": "USE:creative", "đồ họa": "USE:creative",
    "design": "USE:creative", "thiet ke": "USE:creative", "thiết kế": "USE:creative",
    "photoshop": "USE:creative", "premiere": "USE:creative", "render": "USE:creative",
    "dung video": "USE:creative", "dựng video": "USE:creative", "edit video": "USE:creative",
    "autocad": "USE:creative", "3d": "USE:creative",
    "illustrator": "USE:creative", "figma": "USE:creative",
    "after effects": "USE:creative", "ae": "USE:creative",
    "blender": "USE:creative", "solidworks": "USE:creative",
    "revit": "USE:creative", "sketchup": "USE:creative",
    "lightroom": "USE:creative", "davinci": "USE:creative",
    "canva": "USE:creative", "corel": "USE:creative",
    "lam youtube": "USE:creative", "làm youtube": "USE:creative",
    "youtuber": "USE:creative", "content creator": "USE:creative",
    "sang tao noi dung": "USE:creative", "sáng tạo nội dung": "USE:creative",
    "chinh anh": "USE:creative", "chỉnh ảnh": "USE:creative",
    "chup anh": "USE:creative", "chụp ảnh": "USE:creative",
    "nhieu do hoa": "USE:creative", "nhiều đồ họa": "USE:creative",
    "kien truc": "USE:creative", "kiến trúc": "USE:creative",
    "xuat ban": "USE:creative", "xuất bản": "USE:creative",
    "in an": "USE:creative", "in ấn": "USE:creative",

    "lap trinh": "USE:dev", "lập trình": "USE:dev", "code": "USE:dev",
    "coding": "USE:dev", "developer": "USE:dev", "devops": "USE:dev",
    "docker": "USE:dev", "programming": "USE:dev",
    "vscode": "USE:dev", "visual studio": "USE:dev",
    "python": "USE:dev", "java": "USE:dev", "javascript": "USE:dev",
    "android studio": "USE:dev", "xcode": "USE:dev",
    "machine learning": "USE:dev", "ai": "USE:dev",
    "data science": "USE:dev", "deep learning": "USE:dev",
    "may cho dev": "USE:dev", "máy cho dev": "USE:dev",
    "chay nhieu tab": "USE:dev", "chạy nhiều tab": "USE:dev",
    "nhieu cua so": "USE:dev", "nhiều cửa sổ": "USE:dev",
    "terminal": "USE:dev", "command line": "USE:dev",
    "virtual machine": "USE:dev", "may ao": "USE:dev", "máy ảo": "USE:dev",
    "wsl": "USE:dev", "compile": "USE:dev",

    # --- Thuộc tính vật lý ---
    "nhe": "ATTR:light", "nhẹ": "ATTR:light", "mong": "ATTR:light",
    "mỏng": "ATTR:light", "mong nhe": "ATTR:light", "mỏng nhẹ": "ATTR:light",
    "ultrabook": "ATTR:light", "di dong": "ATTR:light", "di động": "ATTR:light",
    "portable": "ATTR:light", "xach tay": "ATTR:light", "xách tay": "ATTR:light",
    "gon": "ATTR:light", "gọn": "ATTR:light", "nho gon": "ATTR:light",
    "nhỏ gọn": "ATTR:light", "de mang": "ATTR:light", "dễ mang": "ATTR:light",
    "mang di": "ATTR:light", "mang đi": "ATTR:light",
    "bo ba lo": "ATTR:light", "bỏ ba lô": "ATTR:light",
    "di chuyen nhieu": "ATTR:light", "di chuyển nhiều": "ATTR:light",
    "mang di hoc": "ATTR:light", "mang đi học": "ATTR:light",
    "mang di lam": "ATTR:light", "mang đi làm": "ATTR:light",

    "pin trau": "ATTR:long_battery", "pin trâu": "ATTR:long_battery",
    "pin lau": "ATTR:long_battery", "pin lâu": "ATTR:long_battery",
    "pin khoe": "ATTR:long_battery", "pin khoẻ": "ATTR:long_battery",
    "battery": "ATTR:long_battery", "dung luong pin": "ATTR:long_battery",
    "dung lượng pin": "ATTR:long_battery",
    "pin tot": "ATTR:long_battery", "pin tốt": "ATTR:long_battery",
    "pin ben": "ATTR:long_battery", "pin bền": "ATTR:long_battery",
    "xai lau": "ATTR:long_battery", "xài lâu": "ATTR:long_battery",
    "dung lau": "ATTR:long_battery", "dùng lâu": "ATTR:long_battery",
    "khong can sac": "ATTR:long_battery", "không cần sạc": "ATTR:long_battery",
    "ca ngay": "ATTR:long_battery", "cả ngày": "ATTR:long_battery",
    "8 tieng": "ATTR:long_battery", "8 tiếng": "ATTR:long_battery",
    "10 tieng": "ATTR:long_battery", "10 tiếng": "ATTR:long_battery",

    "man dep": "ATTR:good_display", "màn đẹp": "ATTR:good_display",
    "man hinh dep": "ATTR:good_display", "màn hình đẹp": "ATTR:good_display",
    "100% srgb": "ATTR:good_display", "oled": "ATTR:good_display",
    "2k": "ATTR:good_display", "4k": "ATTR:good_display", "retina": "ATTR:good_display",
    "mau sac dep": "ATTR:good_display", "màu sắc đẹp": "ATTR:good_display",
    "man sac net": "ATTR:good_display", "màn sắc nét": "ATTR:good_display",
    "xem phim": "ATTR:good_display", "xem film": "ATTR:good_display",
    "giai tri": "ATTR:good_display", "giải trí": "ATTR:good_display",
    "hdr": "ATTR:good_display", "ips": "ATTR:good_display",
    "do sang cao": "ATTR:good_display", "độ sáng cao": "ATTR:good_display",

    "ban phim co": "ATTR:mech_kb", "bàn phím cơ": "ATTR:mech_kb",
    "mechanical": "ATTR:mech_kb",

    "ben": "ATTR:durable", "bền": "ATTR:durable",
    "chat luong": "ATTR:durable", "chất lượng": "ATTR:durable",
    "xai lau": "ATTR:durable", "xài lâu": "ATTR:durable",
    "bao hanh": "ATTR:durable", "bảo hành": "ATTR:durable",
    "khung kim loai": "ATTR:durable", "khung kim loại": "ATTR:durable",
    "nhom": "ATTR:durable", "nhôm": "ATTR:durable",
    "build tot": "ATTR:durable", "build tốt": "ATTR:durable",

    "mat": "ATTR:cool", "mát": "ATTR:cool",
    "khong nong": "ATTR:cool", "không nóng": "ATTR:cool",
    "tan nhiet": "ATTR:cool", "tản nhiệt": "ATTR:cool",
    "tan nhiet tot": "ATTR:cool", "tản nhiệt tốt": "ATTR:cool",
    "it nong": "ATTR:cool", "ít nóng": "ATTR:cool",

    "im": "ATTR:quiet", "yên tĩnh": "ATTR:quiet",
    "khong on": "ATTR:quiet", "không ồn": "ATTR:quiet",
    "it on": "ATTR:quiet", "ít ồn": "ATTR:quiet",
    "yen tinh": "ATTR:quiet", "chay em": "ATTR:quiet", "chạy êm": "ATTR:quiet",

    # --- Thương hiệu ---
    "asus": "BRAND:asus", "acer": "BRAND:acer", "dell": "BRAND:dell",
    "hp": "BRAND:hp", "lenovo": "BRAND:lenovo", "msi": "BRAND:msi",
    "apple": "BRAND:apple", "macbook": "BRAND:apple", "mac": "BRAND:apple",
    "thinkpad": "BRAND:lenovo", "ideapad": "BRAND:lenovo",
    "vivobook": "BRAND:asus", "zenbook": "BRAND:asus",
    "rog": "BRAND:asus", "tuf": "BRAND:asus",
    "legion": "BRAND:lenovo", "nitro": "BRAND:acer", "predator": "BRAND:acer",
    "raider": "BRAND:msi", "stealth": "BRAND:msi",
    "inspiron": "BRAND:dell", "xps": "BRAND:dell", "latitude": "BRAND:dell",
    "pavilion": "BRAND:hp", "envy": "BRAND:hp", "omen": "BRAND:hp",
    "spectre": "BRAND:hp", "elitebook": "BRAND:hp",
    "swift": "BRAND:acer", "aspire": "BRAND:acer",
    "gigabyte": "BRAND:gigabyte", "aorus": "BRAND:gigabyte",
    "samsung": "BRAND:samsung", "galaxy book": "BRAND:samsung",
    "lg": "BRAND:lg", "lg gram": "BRAND:lg",
    "huawei": "BRAND:huawei", "matebook": "BRAND:huawei",
    "surface": "BRAND:microsoft", "microsoft": "BRAND:microsoft",
    "probook": "BRAND:hp", "dragonfly": "BRAND:hp",
    "vostro": "BRAND:dell", "alienware": "BRAND:dell",
    "yoga": "BRAND:lenovo", "slim": "BRAND:lenovo",
    "katana": "BRAND:msi", "bravo": "BRAND:msi",
    "creator": "BRAND:msi", "modern": "BRAND:msi",
    "gram": "BRAND:lg",

    # --- Hệ điều hành ---
    "windows": "OS:windows", "win": "OS:windows", "win11": "OS:windows",
    "windows 11": "OS:windows", "windows 10": "OS:windows",
    "macos": "OS:macos", "mac os": "OS:macos",
    "linux": "OS:linux", "ubuntu": "OS:linux", "fedora": "OS:linux",
    "chrome os": "OS:chromeos", "chromebook": "OS:chromeos",
    "khong os": "OS:none", "không os": "OS:none", "dos": "OS:none",
    "freedos": "OS:none",

    # --- Specs cụ thể ---
    "ssd": "SPEC:ssd", "hdd": "SPEC:hdd", "nvme": "SPEC:ssd",
    "ram 4": "SPEC:ram_4", "4gb ram": "SPEC:ram_4", "4gb": "SPEC:ram_4",
    "ram 8": "SPEC:ram_8", "8gb ram": "SPEC:ram_8", "8gb": "SPEC:ram_8",
    "ram 16": "SPEC:ram_16", "16gb ram": "SPEC:ram_16", "16gb": "SPEC:ram_16",
    "ram 32": "SPEC:ram_32", "32gb ram": "SPEC:ram_32", "32gb": "SPEC:ram_32",
    "ram 64": "SPEC:ram_64", "64gb ram": "SPEC:ram_64", "64gb": "SPEC:ram_64",
    "nhieu ram": "SPEC:ram_16", "nhiều ram": "SPEC:ram_16",

    "120hz": "SPEC:hz_120", "144hz": "SPEC:hz_144", "165hz": "SPEC:hz_165",
    "240hz": "SPEC:hz_240", "300hz": "SPEC:hz_300", "360hz": "SPEC:hz_360",
    "tan so quet cao": "SPEC:hz_120", "tần số quét cao": "SPEC:hz_120",

    "man 13": "SPEC:screen_13", "13 inch": "SPEC:screen_13", "13.3": "SPEC:screen_13",
    "man 14": "SPEC:screen_14", "14 inch": "SPEC:screen_14",
    "man 15": "SPEC:screen_15", "15 inch": "SPEC:screen_15", "15.6": "SPEC:screen_15",
    "man 16": "SPEC:screen_16", "16 inch": "SPEC:screen_16",
    "man 17": "SPEC:screen_17", "17 inch": "SPEC:screen_17", "17.3": "SPEC:screen_17",
    "man to": "SPEC:screen_16", "màn to": "SPEC:screen_16",
    "man lon": "SPEC:screen_16", "màn lớn": "SPEC:screen_16",
    "man nho": "SPEC:screen_13", "màn nhỏ": "SPEC:screen_13",

    "cam ung": "SPEC:touch", "cảm ứng": "SPEC:touch", "touchscreen": "SPEC:touch",
    "2 in 1": "SPEC:2in1", "2in1": "SPEC:2in1", "xoay 360": "SPEC:2in1",
    "gap lai": "SPEC:2in1", "gập lại": "SPEC:2in1", "convertible": "SPEC:2in1",

    "512gb": "SPEC:ssd_512", "ssd 512": "SPEC:ssd_512",
    "1tb": "SPEC:ssd_1tb", "ssd 1tb": "SPEC:ssd_1tb",
    "2tb": "SPEC:ssd_2tb", "ssd 2tb": "SPEC:ssd_2tb",
    "bo nho lon": "SPEC:ssd_1tb", "bộ nhớ lớn": "SPEC:ssd_1tb",
    "nhieu bo nho": "SPEC:ssd_1tb", "nhiều bộ nhớ": "SPEC:ssd_1tb",

    # --- CPU cụ thể ---
    "i5": "SPEC:cpu_i5", "core i5": "SPEC:cpu_i5",
    "i7": "SPEC:cpu_i7", "core i7": "SPEC:cpu_i7",
    "i9": "SPEC:cpu_i9", "core i9": "SPEC:cpu_i9",
    "ryzen 5": "SPEC:cpu_r5", "r5": "SPEC:cpu_r5",
    "ryzen 7": "SPEC:cpu_r7", "r7": "SPEC:cpu_r7",
    "ryzen 9": "SPEC:cpu_r9", "r9": "SPEC:cpu_r9",
    "m1": "SPEC:cpu_m1", "m2": "SPEC:cpu_m2", "m3": "SPEC:cpu_m3",
    "m4": "SPEC:cpu_m4",
    "ultra": "SPEC:cpu_ultra", "intel ultra": "SPEC:cpu_ultra",
    "snapdragon": "SPEC:cpu_snapdragon",

    # --- GPU cụ thể ---
    "rtx 4050": "SPEC:gpu_4050", "rtx 4060": "SPEC:gpu_4060",
    "rtx 4070": "SPEC:gpu_4070", "rtx 4080": "SPEC:gpu_4080",
    "rtx 4090": "SPEC:gpu_4090",
    "rtx 3050": "SPEC:gpu_3050", "rtx 3060": "SPEC:gpu_3060",
    "card roi": "SPEC:dgpu", "card rời": "SPEC:dgpu",
    "vga roi": "SPEC:dgpu", "vga rời": "SPEC:dgpu",
    "gpu roi": "SPEC:dgpu", "gpu rời": "SPEC:dgpu",
    "card on": "SPEC:igpu", "card onboard": "SPEC:igpu",
    "onboard": "SPEC:igpu", "card tich hop": "SPEC:igpu",
    "card tích hợp": "SPEC:igpu",

    # --- Giá (mở rộng cho cách nói VN) ---
    "re": "PRICE:cheap", "rẻ": "PRICE:cheap", "gia re": "PRICE:cheap",
    "giá rẻ": "PRICE:cheap", "binh dan": "PRICE:cheap", "bình dân": "PRICE:cheap",
    "tiet kiem": "PRICE:cheap", "tiết kiệm": "PRICE:cheap",
    "gia tot": "PRICE:cheap", "giá tốt": "PRICE:cheap",
    "gia sinh vien": "PRICE:cheap", "giá sinh viên": "PRICE:cheap",
    "gia mem": "PRICE:cheap", "giá mềm": "PRICE:cheap",
    "gia phai chang": "PRICE:cheap", "giá phải chăng": "PRICE:cheap",
    "re ma tot": "PRICE:cheap", "rẻ mà tốt": "PRICE:cheap",
    "tam trung": "PRICE:mid", "tầm trung": "PRICE:mid",
    "trung binh": "PRICE:mid", "trung bình": "PRICE:mid",
    "vua phai": "PRICE:mid", "vừa phải": "PRICE:mid",
    "cao cap": "PRICE:premium", "cao cấp": "PRICE:premium",
    "premium": "PRICE:premium", "flagship": "PRICE:premium",
    "sang trong": "PRICE:premium", "sang trọng": "PRICE:premium",
    "dang cap": "PRICE:premium", "đẳng cấp": "PRICE:premium",
    "xa xi": "PRICE:premium", "xa xỉ": "PRICE:premium",

    # --- So sánh / Ý định ---
    "so sanh": "INTENT:compare", "so sánh": "INTENT:compare", "compare": "INTENT:compare",
    "khac gi": "INTENT:compare", "khác gì": "INTENT:compare",
    "hon gi": "INTENT:compare", "hơn gì": "INTENT:compare",
    "nen mua": "INTENT:recommend", "nên mua": "INTENT:recommend",
    "tu van": "INTENT:recommend", "tư vấn": "INTENT:recommend",
    "goi y": "INTENT:recommend", "gợi ý": "INTENT:recommend",
    "chon gi": "INTENT:recommend", "chọn gì": "INTENT:recommend",
    "re nhat": "INTENT:cheapest", "rẻ nhất": "INTENT:cheapest",
    "dat nhat": "INTENT:most_expensive", "đắt nhất": "INTENT:most_expensive",
    "manh nhat": "INTENT:most_powerful", "mạnh nhất": "INTENT:most_powerful",
    "dang mua nhat": "INTENT:recommend", "đáng mua nhất": "INTENT:recommend",
    "dang tien": "INTENT:recommend", "đáng tiền": "INTENT:recommend",
    "gia tri tot": "INTENT:recommend", "giá trị tốt": "INTENT:recommend",
    "tot nhat": "INTENT:recommend", "tốt nhất": "INTENT:recommend",
    "ban chay": "INTENT:popular", "bán chạy": "INTENT:popular",
    "pho bien": "INTENT:popular", "phổ biến": "INTENT:popular",
    "nhieu nguoi mua": "INTENT:popular", "nhiều người mua": "INTENT:popular",
    "hot": "INTENT:popular", "best seller": "INTENT:popular",
    "nhe nhat": "INTENT:lightest", "nhẹ nhất": "INTENT:lightest",
    # --- New: Multi-intent / combo phrases ---
    "vừa game vừa học": "USE:gaming",  # Will also match USE:office via "học"
    "vua game vua hoc": "USE:gaming",
    "học và chơi game": "USE:gaming",
    "hoc va choi game": "USE:gaming",
    "game nhẹ": "USE:gaming",
    "game nhe": "USE:gaming",
    "chơi game nhẹ": "USE:gaming",

    # --- Gen-Z / TikTok slang ---
    "xịn sò": "PRICE:premium", "xin so": "PRICE:premium",
    "max setting": "USE:gaming", "max đồ": "USE:gaming", "max do": "USE:gaming",
    "smooth": "USE:gaming", "no lag": "USE:gaming",
    "chill": "USE:office", "nhẹ nhàng": "USE:office", "nhe nhang": "USE:office",
    "ngon bổ rẻ": "PRICE:cheap", "ngon bo re": "PRICE:cheap",
    "deal hot": "PRICE:cheap",
    "xịn xò": "PRICE:premium", "xin xo": "PRICE:premium",
    "đỉnh": "PRICE:premium", "dinh": "PRICE:premium",
    "đỉnh cao": "PRICE:premium", "dinh cao": "PRICE:premium",

    # --- More intent patterns ---
    "nên chọn": "INTENT:recommend", "nen chon": "INTENT:recommend",
    "đề xuất": "INTENT:recommend", "de xuat": "INTENT:recommend",
    "pin trâu nhất": "INTENT:lightest",

    # --- RTX 50 series (new gen) ---
    "rtx 5060": "SPEC:gpu_5060", "rtx 5070": "SPEC:gpu_5070",
    "rtx 5080": "SPEC:gpu_5080", "rtx 5090": "SPEC:gpu_5090",
}


# Từ điển auto-correct lỗi chính tả phổ biến người Việt
TYPO_MAP = {
    "loptop": "laptop", "labtop": "laptop", "laptob": "laptop",
    "lapop": "laptop", "latop": "laptop", "lappop": "laptop",
    "laptoop": "laptop", "lapptop": "laptop",
    "gamiing": "gaming", "gamnig": "gaming", "gamming": "gaming",
    "giming": "gaming", "gameing": "gaming",
    "van phomg": "văn phòng", "vawn phong": "văn phòng",
    "van phog": "văn phòng", "vanphong": "văn phòng",
    "simh vien": "sinh viên", "sinh vein": "sinh viên",
    "sinhvien": "sinh viên", "sin vien": "sinh viên",
    "do hao": "đồ hoạ", "doh hoa": "đồ hoạ",
    "dohoa": "đồ hoạ", "do hoa": "đồ hoạ",
    "thiet ek": "thiết kế", "thiek ke": "thiết kế",
    "thietke": "thiết kế", "thiet ke": "thiết kế",
    "tu vna": "tư vấn", "tuvan": "tư vấn",
    "tu van": "tư vấn", "tuvn": "tư vấn",
    "lam veic": "làm việc", "lamviec": "làm việc",
    "macboo": "macbook", "mackbook": "macbook",
    "macbok": "macbook", "makbook": "macbook",
    "lenova": "lenovo", "lenvoo": "lenovo",
    "lennovo": "lenovo", "lenvo": "lenovo",
    "assus": "asus", "asus": "asus",
    "assu": "asus", "asus": "asus",
    "aple": "apple", "appel": "apple",
    "appl": "apple",
    "photosho": "photoshop", "photoshoop": "photoshop",
    "progamming": "programming", "programing": "programming",
    "ngaan sach": "ngân sách", "ngan sac": "ngân sách",
    "ngansach": "ngân sách",
    "trie": "triệu", "trieu": "triệu",
    "nhe nhe": "nhẹ", "nhee": "nhẹ",
    "pin chau": "pin trâu", "pin taru": "pin trâu",
    "mam hinh": "màn hình", "man hihh": "màn hình",
    "manhihh": "màn hình", "manhinh": "màn hình",
    # More common typos
    "nhee": "nhẹ", "nheẹ": "nhẹ",
    "goia y": "gợi ý", "goiy": "gợi ý",
    "chinh anh": "chỉnh ảnh",
    "so sanh": "so sánh",
    "duoi": "dưới",
    "toi da": "tối đa",
    "manh": "mạnh",
    "bam phim": "bàn phím",
}

